spring:
  application:
    name: blocking-extension
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/blocking?userUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: root
      password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  #    database-platform: org.hibernate.dialect.MySQL8Dialect
#  data:
#    redis:
#      host: localhost
#      port: 6380
vue:
  url: http://localhost:3000

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://blocking-extension.c96yas0i4u6o.ap-northeast-2.rds.amazonaws.com/blocking?userUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-timeout: 3000
      username: admin
      password: fnffnfkffk98*
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
server:
  port: 80
